Add timezone, locale, version app, about.html, author.html, readme.md
dmitryS1666/test-guru pull request #1
Opened 2017-11-13 20:20 UTC by dmitryS1666

2017-11-13 22:02 UTC, psylone requested changes

2017-11-13 22:02 UTC, psylone commented on .idea/misc.xml
> +</project>
`.idea` необходимо удалить из репозитория.

2017-11-13 22:02 UTC, psylone commented on README.md
> + - Questions (вопросы)
Как пользователь будет отвечать на вопросы? Где будет храниться информация о прохождении теста?

2017-11-13 22:02 UTC, psylone commented on config/application.rb
> +require_relative 'initializers/version'
Инишиалайзеры загружаются автоматически. Вручную реквайрить их не нужно.

2017-11-13 22:02 UTC, psylone commented on config/initializers/version.rb
> +end
По идее, нужно прийти к чему-то такому:

```ruby
TestGuru.version # => '1.0.0'
```

2017-11-13 22:02 UTC, psylone commented on log/development.log
> +Started GET "/" for 127.0.0.1 at 2017-11-13 22:20:33 +0300
Логам также в репозитории не место.

2017-11-13 22:02 UTC, psylone commented on public/about.html
> +    <a href="http://www.thinknetica.com/">Thinknetica</a>
Пожалуйста, сделай так чтобы ссылка открывалась в новой вкладке.

2017-11-13 22:02 UTC, psylone commented on public/about/author.html
> +
Должна быть ссылка на GitHub профиль.

2017-11-14 13:51 UTC, vkurennov approved these changes

2017-11-14 13:51 UTC, vkurennov commented on log/development.log
> +Started GET "/" for 127.0.0.1 at 2017-11-13 22:20:33 +0300
удали папку log из репозитория (git rm), затем сделай коммит, затем добавь папку log/ в .gitignore и снова сделай коммит

2017-11-15 09:12 UTC, merged