lesson 7
dmitryS1666/test-guru pull request #6
Opened 2017-12-18 08:30 UTC by dmitryS1666

init commit

2017-12-18 22:14 UTC, psylone requested changes

2017-12-18 22:14 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "All questions: #{@questions.each { |question| question}}"
Нет смысла передавать такой блок, здесь он ничего не делает. Сам метод `each` возвращает коллекцию, поэтому без блока и вызова `each` будет тот же результат.

2017-12-18 22:14 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "Question number #{params[:id]}: #{@question[0].body}"
Проверь этот метод.

2017-12-18 22:14 UTC, psylone commented on app/models/question.rb
> +  scope :by_test_id, -> (test_id) { where(test_id: test_id)}
Особого смысла в таком скоупе нет, достаточно `where`.

2017-12-18 22:14 UTC, psylone commented on app/controllers/questions_controller.rb
> +  def find_question_by_id
Обычно метод называют просто `find_question`.

2017-12-18 22:14 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @questions = Question.by_test_id(params[:test_id])
Если этот обратный вызов используется только перед методом `show`, то по логике мы должны выбрать конкретный вопрос который хотим показать с помощью идентификатора, переданного в параметрах.

2017-12-19 11:21 UTC, dmitryS1666 commented on app/controllers/questions_controller.rb
> +    render plain: "All questions: #{@questions.each { |question| question}}"
сделал each и блок, т.к. в @questions находится объект класса Вопросы.
перенес блок в call_back - теперь в @questions - список вопросов

2017-12-19 11:32 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "All questions: #{@questions.each { |question| question}}"
Вообще там релейшен должен быть, который откладывает загрузку данных до последнего момента и позволяет сцепляться с другими методами ActiveRecord. Суть в том что само выражение `collection.each { |element| element }` ничего не делает полезного поскольку в блоке мы ничего не делаем с элементом. Если нужно заставить ActiveRecord выполнить запрос, можно вызвать метод `to_a`.

2017-12-19 17:56 UTC, psylone approved these changes

2017-12-19 17:56 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id]).where(test_id: params[:test_id])
`where` здесь не нужен. Вопрос принадлежит к конкретному тесту и если будет нужно найти тест, мы сможем опираться на поле `test_id` у вопроса.

2017-12-19 17:56 UTC, psylone commented on app/controllers/questions_controller.rb
> +    @questions = Question.where(test_id: params[:test_id]).each { |question| question }
Блок в `each` не делает никакой полезной работы.

2017-12-19 17:56 UTC, psylone commented on app/controllers/questions_controller.rb
> +    render plain: "All questions: #{@questions}"
Будет лучше вызвать здесь `to_a` чтобы загрузить данные из БД.

2017-12-20 17:56 UTC, merged