Lesson 10
dmitryS1666/test-guru pull request #9
Opened 2018-01-13 09:52 UTC by dmitryS1666

init lesson_10

2018-01-13 14:35 UTC, psylone requested changes

2018-01-13 14:35 UTC, psylone commented on app/controllers/users_controller.rb
> +    if @user.save
После создания пользователя, его идентификатор необходимо добавить в сессию.

2018-01-13 14:35 UTC, psylone commented on app/views/sessions/_form.html.erb
> +    <%= flash_alert %>
Стоит вытащить отображение флэш сообщений в главный шаблон приложения.

2018-01-13 14:35 UTC, psylone commented on app/helpers/application_helper.rb
> +  def flash_alert
Подумай как можно сделать этот хэлпер более универсальным, чтобы можно было выводить не только алерты, но и информационные сообщения.

2018-01-13 14:35 UTC, psylone commented on app/controllers/tests_controller.rb
Проверь метод `start`.

2018-01-13 14:35 UTC, psylone commented on app/views/layouts/application.html.erb
> +    </div>
Вынеси навигацию во фрагмент представления.

2018-01-13 14:35 UTC, psylone commented on app/models/user/auth.rb
> +module User::Auth
Этот модуль теперь не нужен, поскольку мы используем `has_secure_password`.

2018-01-13 14:35 UTC, psylone commented on app/models/user.rb
> +  has_secure_password
Разве [`has_secure_password`](https://sourcegraph.com/github.com/rails/rails/-/blob/activemodel/lib/active_model/secure_password.rb) отвечает за валидацию уникальности `email`?

2018-01-13 14:35 UTC, psylone commented on app/models/user.rb
> +  has_secure_password
Так или иначе, понадобится уникальный индекс.

2018-01-13 14:35 UTC, psylone commented on app/controllers/tests_controller.rb
> +  before_action :authenticate_user!
Можно сделать возможным просматривать список тестов всем пользователям, даже если у них нет сессии.

2018-01-14 20:38 UTC, dmitryS1666 commented on app/models/user.rb
> +  has_secure_password
случайно снес ((

2018-01-14 23:11 UTC, psylone approved these changes

2018-01-15 11:17 UTC, merged